import { readFileSync, writeFileSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))

function mergeArticles(filePath, newArticles) {
  const data = JSON.parse(readFileSync(filePath, 'utf8'))
  const existingIds = new Set(data.articles.map(a => a.id))
  let added = 0
  for (const article of newArticles) {
    if (!existingIds.has(article.id)) {
      data.articles.push(article)
      added++
    }
  }
  data.articles.sort((a, b) => parseInt(a.number) - parseInt(b.number))
  writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8')
  console.log(`  ${filePath.split('/').pop()}: +${added} articles`)
}

// ============================================================
// USA — U.S. Constitution
// ============================================================
const usConstitution = [
  { id: 'usc_1', number: '1', title: 'Legislative Power', text: 'All legislative Powers herein granted shall be vested in a Congress of the United States, which shall consist of a Senate and House of Representatives.', tags: ['congress', 'senate', 'house', 'legislative', 'power'], relatedArticles: ['usc_2', 'usc_3'] },
  { id: 'usc_2', number: '2', title: 'Executive Power', text: 'The executive Power shall be vested in a President of the United States of America. He shall hold his Office during the Term of four Years, and, together with the Vice President, chosen for the same Term, be elected as provided in this Constitution.', tags: ['president', 'executive', 'term', 'election'], relatedArticles: ['usc_1', 'usc_3'] },
  { id: 'usc_3', number: '3', title: 'Judicial Power', text: 'The judicial Power of the United States, shall be vested in one supreme Court, and in such inferior Courts as the Congress may from time to time ordain and establish. The Judges, both of the supreme and inferior Courts, shall hold their Offices during good Behaviour.', tags: ['supreme court', 'judicial', 'courts', 'judges'], relatedArticles: ['usc_1', 'usc_2'] },
  { id: 'usc_am1', number: 'Amendment I', title: 'Freedom of Speech, Religion, Press', text: 'Congress shall make no law respecting an establishment of religion, or prohibiting the free exercise thereof; or abridging the freedom of speech, or of the press; or the right of the people peaceably to assemble, and to petition the Government for a redress of grievances.', tags: ['freedom', 'speech', 'religion', 'press', 'assembly'], relatedArticles: ['usc_am4', 'usc_am14'] },
  { id: 'usc_am2', number: 'Amendment II', title: 'Right to Bear Arms', text: 'A well regulated Militia, being necessary to the security of a free State, the right of the people to keep and bear Arms, shall not be infringed.', tags: ['guns', 'arms', 'militia', 'second amendment', 'weapons'], relatedArticles: ['usc_am1'] },
  { id: 'usc_am4', number: 'Amendment IV', title: 'Search and Seizure', text: 'The right of the people to be secure in their persons, houses, papers, and effects, against unreasonable searches and seizures, shall not be violated, and no Warrants shall issue, but upon probable cause, supported by Oath or affirmation, and particularly describing the place to be searched, and the persons or things to be seized.', tags: ['search', 'seizure', 'warrant', 'privacy', 'fourth amendment'], relatedArticles: ['usc_am5', 'usc_am6'] },
  { id: 'usc_am5', number: 'Amendment V', title: 'Due Process, Self-Incrimination', text: 'No person shall be held to answer for a capital, or otherwise infamous crime, unless on a presentment or indictment of a Grand Jury; nor shall any person be subject for the same offence to be twice put in jeopardy of life or limb; nor shall be compelled in any criminal case to be a witness against himself, nor be deprived of life, liberty, or property, without due process of law; nor shall private property be taken for public use, without just compensation.', tags: ['due process', 'self-incrimination', 'double jeopardy', 'grand jury', 'fifth amendment'], relatedArticles: ['usc_am4', 'usc_am6'] },
  { id: 'usc_am6', number: 'Amendment VI', title: 'Right to Fair Trial', text: 'In all criminal prosecutions, the accused shall enjoy the right to a speedy and public trial, by an impartial jury of the State and district wherein the crime shall have been committed; and to be informed of the nature and cause of the accusation; to be confronted with the witnesses against him; to have compulsory process for obtaining witnesses in his favor, and to have the Assistance of Counsel for his defence.', tags: ['fair trial', 'jury', 'speedy trial', 'counsel', 'sixth amendment'], relatedArticles: ['usc_am5', 'usc_am8'] },
  { id: 'usc_am8', number: 'Amendment VIII', title: 'Cruel and Unusual Punishment', text: 'Excessive bail shall not be required, nor excessive fines imposed, nor cruel and unusual punishments inflicted.', tags: ['cruel punishment', 'bail', 'fines', 'eighth amendment', 'punishment'], relatedArticles: ['usc_am6'] },
  { id: 'usc_am14', number: 'Amendment XIV', title: 'Equal Protection and Due Process', text: 'All persons born or naturalized in the United States, and subject to the jurisdiction thereof, are citizens of the United States and of the State wherein they reside. No State shall make or enforce any law which shall abridge the privileges or immunities of citizens of the United States; nor shall any State deprive any person of life, liberty, or property, without due process of law; nor deny to any person within its jurisdiction the equal protection of the laws.', tags: ['equal protection', 'citizenship', 'due process', 'fourteenth amendment', 'civil rights'], relatedArticles: ['usc_am1', 'usc_am5'] },
]

// ============================================================
// USA — Title 18 Criminal
// ============================================================
const title18 = [
  { id: 't18_1', number: '1', title: 'Crimes and Criminal Procedure', text: 'This title deals with crimes and criminal procedure in the United States federal system. It covers offenses against the United States government, its property, and its citizens.', tags: ['crimes', 'criminal', 'federal', 'procedure'], relatedArticles: [] },
  { id: 't18_2', number: '2', title: 'Principals — Aiding and Abetting', text: 'Whoever commits an offense against the United States or aids, abets, counsels, commands, induces or procures its commission, is punishable as a principal. Whoever willfully causes an act to be done which if directly performed by him or another would be an offense against the United States, is punishable as a principal.', tags: ['aiding', 'abetting', 'principal', 'accomplice', 'conspiracy'], relatedArticles: ['t18_3', 't18_4'] },
  { id: 't18_4', number: '4', title: 'Misprision of Felony', text: 'Whoever, having knowledge of the actual commission of a felony cognizable by a court of the United States, conceals and does not as soon as possible make known the same to some judge or other person in civil or military authority under the United States, shall be fined under this title or imprisoned not more than three years, or both.', tags: ['felony', 'concealment', 'misprision', 'reporting'], relatedArticles: ['t18_2'] },
  { id: 't18_111', number: '111', title: 'Assaulting Federal Officers', text: 'Whoever forcibly assaults, resists, opposes, impedes, intimidates, or interferes with any person designated in section 1114 of this title while engaged in or on account of the performance of official duties shall be fined under this title or imprisoned not more than 8 years, or both.', tags: ['assault', 'federal officer', 'resistance', 'intimidation'], relatedArticles: ['t18_1114'] },
  { id: 't18_113', number: '113', title: 'Assault Within Maritime and Territorial Jurisdiction', text: 'Assault in the special maritime and territorial jurisdiction of the United States is punishable as follows: Assault with intent to commit murder or a felony, by imprisonment for not more than twenty years. Assault with intent to commit any felony, by imprisonment for not more than ten years. Assault with a dangerous weapon, with intent to do bodily harm, by imprisonment for not more than ten years.', tags: ['assault', 'maritime', 'territory', 'dangerous weapon'], relatedArticles: ['t18_111'] },
  { id: 't18_201', number: '201', title: 'Bribery of Public Officials', text: 'Whoever corruptly gives, offers or promises anything of value to any public official or person who has been selected to be a public official, with intent to influence any official act shall be fined under this title or not more than three times the monetary equivalent of the thing of value, whichever is greater, or imprisoned for not more than fifteen years, or both.', tags: ['bribery', 'corruption', 'public official', 'federal crime'], relatedArticles: ['t18_203', 't18_666'] },
  { id: 't18_371', number: '371', title: 'Conspiracy to Commit Federal Offense', text: 'If two or more persons conspire either to commit any offense against the United States, or to defraud the United States, or any agency thereof in any manner or for any purpose, and one or more of such persons do any act to effect the object of the conspiracy, each shall be fined under this title or imprisoned not more than five years, or both.', tags: ['conspiracy', 'federal offense', 'fraud', 'five years'], relatedArticles: ['t18_2', 't18_1349'] },
  { id: 't18_1001', number: '1001', title: 'False Statements to Federal Government', text: 'Whoever, in any matter within the jurisdiction of the executive, legislative, or judicial branch of the Government of the United States, knowingly and willfully falsifies, conceals, or covers up by any trick, scheme, or device a material fact; makes any materially false, fictitious, or fraudulent statement or representation; or makes or uses any false writing or document knowing the same to contain any materially false, fictitious, or fraudulent statement or entry; shall be fined under this title, imprisoned not more than 5 years.', tags: ['false statements', 'lying', 'federal government', 'fraud', 'five years'], relatedArticles: ['t18_1621'] },
  { id: 't18_1030', number: '1030', title: 'Computer Fraud and Abuse', text: 'Whoever knowingly accesses a computer without authorization or exceeds authorized access, and thereby obtains information contained in a financial record of a financial institution; information from any department or agency of the United States; or information from any protected computer shall be punished. This section covers unauthorized computer access, computer fraud, and damage to protected computers.', tags: ['computer fraud', 'hacking', 'cybercrime', 'unauthorized access', 'internet'], relatedArticles: ['t18_1029'] },
  { id: 't18_1341', number: '1341', title: 'Mail Fraud', text: 'Whoever, having devised or intending to devise any scheme or artifice to defraud, or for obtaining money or property by means of false or fraudulent pretenses, representations, or promises, for the purpose of executing such scheme or artifice or attempting so to do, places in any post office or authorized depository for mail matter, any matter or thing whatever to be sent or delivered by the Postal Service shall be fined under this title or imprisoned not more than 20 years, or both.', tags: ['mail fraud', 'scheme', 'fraud', 'postal service', 'twenty years'], relatedArticles: ['t18_1343'] },
  { id: 't18_1343', number: '1343', title: 'Wire Fraud', text: 'Whoever, having devised or intending to devise any scheme or artifice to defraud, or for obtaining money or property by means of false or fraudulent pretenses, transmits or causes to be transmitted by means of wire, radio, or television communication in interstate or foreign commerce, any writings, signs, signals, pictures, or sounds for the purpose of executing such scheme or artifice, shall be fined under this title or imprisoned not more than 20 years, or both.', tags: ['wire fraud', 'internet fraud', 'scheme', 'telecommunications', 'twenty years'], relatedArticles: ['t18_1341'] },
  { id: 't18_1349', number: '1349', title: 'Conspiracy to Commit Wire or Mail Fraud', text: 'Any person who attempts or conspires to commit any offense under this chapter shall be subject to the same penalties as those prescribed for the offense, the commission of which was the object of the attempt or conspiracy.', tags: ['conspiracy', 'wire fraud', 'mail fraud', 'attempt'], relatedArticles: ['t18_1341', 't18_1343'] },
  { id: 't18_1503', number: '1503', title: 'Obstruction of Justice', text: 'Whoever corruptly, or by threats or force, or by any threatening letter or communication, endeavors to influence, intimidate, or impede any grand or petit juror, or officer in or of any court of the United States, in the discharge of his duty, or injures any such grand or petit juror in his person or property on account of any verdict or indictment assented to by him, shall be fined under this title or imprisoned not more than 10 years, or both.', tags: ['obstruction', 'justice', 'jury tampering', 'court', 'ten years'], relatedArticles: ['t18_1512'] },
  { id: 't18_1512', number: '1512', title: 'Witness Tampering', text: 'Whoever knowingly uses intimidation, threatens, or corruptly persuades another person, or attempts to do so, or engages in misleading conduct toward another person, with intent to influence, delay, or prevent the testimony of any person in an official proceeding; cause or induce any person to withhold testimony, or withhold a record, document, or other object, from an official proceeding shall be fined under this title or imprisoned not more than 20 years, or both.', tags: ['witness tampering', 'intimidation', 'official proceeding', 'testimony'], relatedArticles: ['t18_1503'] },
  { id: 't18_1621', number: '1621', title: 'Perjury', text: 'Whoever having taken an oath before a competent tribunal, officer, or person, in any case in which a law of the United States authorizes an oath to be administered, that he will testify, declare, depose, or certify truly, willfully and contrary to such oath states or subscribes any material matter which he does not believe to be true is guilty of perjury and shall, except as otherwise expressly provided by law, be fined under this title or imprisoned not more than five years, or both.', tags: ['perjury', 'lying under oath', 'testimony', 'false statement'], relatedArticles: ['t18_1001'] },
]

// ============================================================
// USA — Title 42 Civil Rights
// ============================================================
const title42 = [
  { id: 't42_1981', number: '1981', title: 'Equal Rights Under the Law', text: 'All persons within the jurisdiction of the United States shall have the same right in every State and Territory to make and enforce contracts, to sue, be parties, give evidence, and to the full and equal benefit of all laws and proceedings for the security of persons and property as is enjoyed by white citizens, and shall be subject to like punishment, pains, penalties, taxes, licenses, and exactions of every kind, and to no other.', tags: ['equal rights', 'civil rights', 'discrimination', 'contracts', 'race'], relatedArticles: ['t42_1983'] },
  { id: 't42_1983', number: '1983', title: 'Civil Action for Deprivation of Rights', text: 'Every person who, under color of any statute, ordinance, regulation, custom, or usage, of any State or Territory or the District of Columbia, subjects, or causes to be subjected, any citizen of the United States or other person within the jurisdiction thereof to the deprivation of any rights, privileges, or immunities secured by the Constitution and laws, shall be liable to the party injured in an action at law, suit in equity, or other proper proceeding for redress.', tags: ['civil rights', 'deprivation', 'state action', 'constitutional rights', 'lawsuit'], relatedArticles: ['t42_1981', 't42_1985'] },
  { id: 't42_2000e', number: '2000e', title: 'Title VII — Employment Discrimination', text: 'It shall be an unlawful employment practice for an employer to fail or refuse to hire or to discharge any individual, or otherwise to discriminate against any individual with respect to his compensation, terms, conditions, or privileges of employment, because of such individual\'s race, color, religion, sex, or national origin.', tags: ['employment discrimination', 'race', 'sex', 'religion', 'title VII', 'hiring'], relatedArticles: ['t42_12101'] },
  { id: 't42_12101', number: '12101', title: 'Americans with Disabilities Act — Findings', text: 'The Congress finds that physical or mental disabilities in no way diminish a person\'s right to fully participate in all aspects of society, yet many people with physical or mental disabilities have been precluded from doing so because of discrimination; others who have a record of a disability or are regarded as having a disability also have been subjected to discrimination.', tags: ['disability', 'ADA', 'discrimination', 'accessibility', 'employment'], relatedArticles: ['t42_2000e'] },
  { id: 't42_12112', number: '12112', title: 'ADA — Prohibition on Discrimination', text: 'No covered entity shall discriminate against a qualified individual on the basis of disability in regard to job application procedures, the hiring, advancement, or discharge of employees, employee compensation, job training, and other terms, conditions, and privileges of employment.', tags: ['ADA', 'disability discrimination', 'employment', 'accommodation', 'qualified individual'], relatedArticles: ['t42_12101'] },
]

// ============================================================
// USA — Title 8 Immigration
// ============================================================
const title8 = [
  { id: 't8_1101', number: '1101', title: 'Definitions — Immigration', text: 'As used in this chapter, the term "alien" means any person not a citizen or national of the United States. The term "immigrant" means every alien except those specified as nonimmigrant. The term "lawful permanent resident" means the status of having been lawfully accorded the privilege of residing permanently in the United States as an immigrant.', tags: ['alien', 'immigrant', 'lawful permanent resident', 'green card', 'citizenship'], relatedArticles: ['t8_1182'] },
  { id: 't8_1182', number: '1182', title: 'Inadmissible Aliens', text: 'The following classes of aliens shall be ineligible to receive visas and shall be excluded from admission into the United States: aliens who are inadmissible on health-related grounds; aliens convicted of, or who admit having committed, a crime involving moral turpitude; aliens who have been convicted of two or more offenses for which the aggregate sentences to confinement were five years or more; aliens who the consular officer or the Attorney General knows or has reason to believe seek to enter the United States to engage in espionage.', tags: ['inadmissible', 'visa denial', 'deportation', 'grounds of inadmissibility', 'exclusion'], relatedArticles: ['t8_1227'] },
  { id: 't8_1227', number: '1227', title: 'Deportable Aliens', text: 'Any alien in the United States shall, upon the order of the Attorney General, be removed if the alien is within one or more of the following classes of deportable aliens: Any alien who was inadmissible at the time of entry or adjustment of status; any alien who is convicted of a crime involving moral turpitude committed within five years after the date of admission; any alien who at any time after admission is convicted of two or more crimes involving moral turpitude.', tags: ['deportation', 'removal', 'deportable', 'criminal alien', 'moral turpitude'], relatedArticles: ['t8_1182', 't8_1229'] },
  { id: 't8_1325', number: '1325', title: 'Improper Entry by Alien', text: 'Any alien who enters or attempts to enter the United States at any time or place other than as designated by immigration officers, or eludes examination or inspection by immigration officers, or attempts to enter or obtains entry to the United States by a willfully false or misleading representation or the willful concealment of a material fact, shall, for the first commission of any such offense, be fined under title 18 or imprisoned not more than 6 months, or both.', tags: ['illegal entry', 'border crossing', 'unauthorized entry', 'immigration violation'], relatedArticles: ['t8_1326'] },
  { id: 't8_1326', number: '1326', title: 'Reentry of Removed Aliens', text: 'Any alien who has been denied admission, excluded, deported, or removed or has departed the United States while an order of exclusion, deportation, or removal is outstanding, and thereafter enters, attempts to enter, or is at any time found in the United States, unless the Attorney General has expressly consented to such alien\'s reentry shall be fined under title 18, or imprisoned not more than 2 years, or both.', tags: ['reentry', 'deported alien', 'illegal reentry', 'removal order'], relatedArticles: ['t8_1325'] },
]

// ============================================================
// BRAZIL — Top 50 key articles (supplement existing)
// ============================================================
const brazilConstituicao = [
  { id: 'cf_150', number: '150', title: 'Limitações ao Poder de Tributar', text: 'Sem prejuízo de outras garantias asseguradas ao contribuinte, é vedado à União, aos Estados, ao Distrito Federal e aos Municípios: I - exigir ou aumentar tributo sem lei que o estabeleça; II - instituir tratamento desigual entre contribuintes que se encontrem em situação equivalente; III - cobrar tributos em relação a fatos geradores ocorridos antes do início da vigência da lei que os houver instituído; IV - utilizar tributo com efeito de confisco; V - estabelecer limitações ao tráfego de pessoas ou bens, por meio de tributos interestaduais ou intermunicipais.', tags: ['tributo', 'imposto', 'tributação', 'contribuinte', 'fiscal'], relatedArticles: ['cf_145', 'cf_153'] },
  { id: 'cf_37', number: '37', title: 'Administração Pública', text: 'A administração pública direta e indireta de qualquer dos Poderes da União, dos Estados, do Distrito Federal e dos Municípios obedecerá aos princípios de legalidade, impessoalidade, moralidade, publicidade e eficiência. II - a investidura em cargo ou emprego público depende de aprovação prévia em concurso público de provas ou de provas e títulos. IV - durante o prazo improrrogável previsto no edital de convocação, aquele aprovado em concurso público de provas ou de provas e títulos será convocado com prioridade sobre novos concursados para assumir cargo ou emprego, na carreira.', tags: ['administração pública', 'concurso público', 'legalidade', 'moralidade', 'servidor'], relatedArticles: ['cf_5', 'cf_41'] },
  { id: 'cf_144', number: '144', title: 'Segurança Pública', text: 'A segurança pública, dever do Estado e de todos, é exercida para a preservação da ordem pública e da incolumidade das pessoas e do patrimônio, através dos seguintes órgãos: I - polícia federal; II - polícia rodoviária federal; III - polícia ferroviária federal; IV - polícias civis; V - polícias militares e corpos de bombeiros militares; VI - polícias penais federal, estaduais e distrital.', tags: ['segurança pública', 'polícia', 'ordem pública', 'estado'], relatedArticles: ['cf_5', 'cf_37'] },
]

const brazilCodigoPenal = [
  { id: 'cp_155', number: '155', title: 'Furto', text: 'Subtrair, para si ou para outrem, coisa alheia móvel: Pena - reclusão, de um a quatro anos, e multa. § 1º - A pena aumenta-se de um terço, se o crime é praticado durante o repouso noturno. § 4º - A pena é de reclusão de dois a oito anos, e multa, se o furto é cometido: I - com destruição ou rompimento de obstáculo; II - com abuso de confiança, ou mediante fraude, escalada ou destreza; III - com emprego de chave falsa; IV - mediante concurso de duas ou mais pessoas.', tags: ['furto', 'subtração', 'coisa', 'reclusão', 'crime contra patrimônio'], relatedArticles: ['cp_157', 'cp_171'] },
  { id: 'cp_217a', number: '217-A', title: 'Estupro de Vulnerável', text: 'Ter conjunção carnal ou praticar outro ato libidinoso com menor de 14 anos: Pena - reclusão, de 8 a 15 anos. § 1º Incorre na mesma pena quem pratica as ações descritas no caput com alguém que, por enfermidade ou deficiência mental, não tem o necessário discernimento para a prática do ato, ou que, por qualquer outra causa, não pode oferecer resistência. § 3º Se da conduta resulta lesão corporal de natureza grave: Pena - reclusão, de 10 a 20 anos. § 4º Se da conduta resulta morte: Pena - reclusão, de 12 a 30 anos.', tags: ['estupro', 'vulnerável', 'menor', 'crime sexual', 'proteção'], relatedArticles: ['cp_213', 'eca_217'] },
  { id: 'cp_302', number: '302', title: 'Homicídio Culposo na Direção de Veículo', text: 'Praticar homicídio culposo na direção de veículo automotor: Penas - detenção ou proibição de se obter a permissão ou a habilitação para dirigir veículo automotor. § 1o No homicídio culposo cometido na direção de veículo automotor, a pena é aumentada de um terço à metade, se o agente: I - não possuir Permissão para Dirigir ou Carteira de Habilitação; II - praticá-lo em faixa de pedestres ou na calçada; III - deixar de prestar socorro, quando possível fazê-lo sem risco pessoal, à vítima do acidente.', tags: ['homicídio culposo', 'trânsito', 'direção', 'veículo', 'acidente'], relatedArticles: ['cp_121', 'cp_303'] },
]

// ============================================================
// PORTUGAL — Top 50 key articles
// ============================================================
const portugalConstituicao = [
  { id: 'cfpt_13', number: '13', title: 'Princípio da Igualdade', text: 'Todos os cidadãos têm a mesma dignidade social e são iguais perante a lei. Ninguém pode ser privilegiado, beneficiado, prejudicado, privado de qualquer direito ou isento de qualquer dever em razão de ascendência, sexo, raça, língua, território de origem, religião, convicções políticas ou ideológicas, instrução, situação económica, condição social ou orientação sexual.', tags: ['igualdade', 'discriminação', 'dignidade', 'direitos', 'cidadãos'], relatedArticles: ['cfpt_1', 'cfpt_25'] },
  { id: 'cfpt_24', number: '24', title: 'Direito à Vida', text: 'A vida humana é inviolável. Em caso algum haverá pena de morte.', tags: ['vida', 'pena de morte', 'inviolável', 'direito fundamental'], relatedArticles: ['cfpt_25', 'cfpt_27'] },
  { id: 'cfpt_25', number: '25', title: 'Direito à Integridade Pessoal', text: 'A integridade moral e física das pessoas é inviolável. Ninguém pode ser submetido a tortura, nem a penas ou tratamentos desumanos. Ninguém pode ser submetido a experiências médicas ou científicas sem o seu consentimento esclarecido.', tags: ['integridade', 'tortura', 'tratamento desumano', 'consentimento', 'física'], relatedArticles: ['cfpt_24', 'cfpt_27'] },
  { id: 'cfpt_26', number: '26', title: 'Outros Direitos Pessoais', text: 'A todos são reconhecidos os direitos à identidade pessoal, ao desenvolvimento da personalidade, à capacidade civil, à cidadania, ao bom nome e reputação, à imagem, à palavra, à reserva da intimidade da vida privada e familiar e à protecção legal contra quaisquer formas de discriminação. A lei estabelecerá garantias efectivas contra a obtenção e utilização abusivas, ou contrárias à dignidade humana, de informações relativas às pessoas e famílias.', tags: ['identidade', 'privacidade', 'reputação', 'imagem', 'personalidade'], relatedArticles: ['cfpt_25', 'cfpt_35'] },
  { id: 'cfpt_35', number: '35', title: 'Utilização da Informática', text: 'Todos os cidadãos têm o direito de acesso aos dados informatizados que lhes digam respeito, podendo exigir a sua rectificação e actualização, e o direito de conhecer a finalidade a que se destinam. A informática não pode ser utilizada para tratamento de dados referentes a convicções filosóficas ou políticas, filiação partidária ou sindical, fé religiosa, vida privada e origem étnica, salvo mediante consentimento expresso do titular.', tags: ['dados pessoais', 'informática', 'privacidade', 'RGPD', 'proteção de dados'], relatedArticles: ['cfpt_26'] },
]

const portugalCodigoPenal = [
  { id: 'cppt_131', number: '131', title: 'Homicídio', text: 'Quem matar outra pessoa é punido com pena de prisão de 8 a 16 anos.', tags: ['homicídio', 'morte', 'matar', 'prisão', 'crime'], relatedArticles: ['cppt_132', 'cppt_133'] },
  { id: 'cppt_132', number: '132', title: 'Homicídio Qualificado', text: 'Se a morte for produzida em circunstâncias que revelem especial censurabilidade ou perversidade, o agente é punido com pena de prisão de 12 a 25 anos. É susceptível de revelar a especial censurabilidade ou perversidade a circunstância de o agente: ser determinado por avidez, pelo prazer de matar ou de causar sofrimento, para excitação ou para satisfação do instinto sexual; ter em vista a facilitação ou encobrir a prática de um crime; praticar o facto juntamente com, pelo menos, mais 2 pessoas.', tags: ['homicídio qualificado', 'premeditação', 'agravante', 'prisão', 'crime'], relatedArticles: ['cppt_131', 'cppt_133'] },
  { id: 'cppt_203', number: '203', title: 'Furto', text: 'Quem, com ilegítima intenção de apropriação para si ou para outra pessoa, subtrair coisa móvel alheia, é punido com pena de prisão até 3 anos ou com pena de multa. A tentativa é punível. O procedimento criminal depende de queixa.', tags: ['furto', 'subtração', 'coisa móvel', 'prisão', 'queixa'], relatedArticles: ['cppt_204', 'cppt_210'] },
  { id: 'cppt_210', number: '210', title: 'Roubo', text: 'Quem, com ilegítima intenção de apropriação para si ou para outra pessoa, subtrair, ou constranger a que lhe seja entregue, coisa móvel alheia, por meio de violência contra uma pessoa, de ameaça com perigo iminente para a vida ou para a integridade física, ou pondo-a na impossibilidade de resistir, é punido com pena de prisão de 1 a 8 anos.', tags: ['roubo', 'violência', 'ameaça', 'coerção', 'crime contra patrimônio'], relatedArticles: ['cppt_203', 'cppt_211'] },
]

// ============================================================
// SPAIN — Top 50 key articles
// ============================================================
const spainConstitucion = [
  { id: 'ces_14', number: '14', title: 'Igualdad ante la Ley', text: 'Los españoles son iguales ante la ley, sin que pueda prevalecer discriminación alguna por razón de nacimiento, raza, sexo, religión, opinión o cualquier otra condición o circunstancia personal o social.', tags: ['igualdad', 'discriminación', 'derechos', 'ciudadanos', 'constitución'], relatedArticles: ['ces_1', 'ces_9'] },
  { id: 'ces_15', number: '15', title: 'Derecho a la Vida', text: 'Todos tienen derecho a la vida y a la integridad física y moral, sin que, en ningún caso, puedan ser sometidos a tortura ni a penas o tratos inhumanos o degradantes. Queda abolida la pena de muerte, salvo lo que puedan disponer las leyes penales militares para tiempos de guerra.', tags: ['vida', 'integridad', 'tortura', 'pena de muerte', 'derechos fundamentales'], relatedArticles: ['ces_14', 'ces_17'] },
  { id: 'ces_17', number: '17', title: 'Derecho a la Libertad', text: 'Toda persona tiene derecho a la libertad y a la seguridad. Nadie puede ser privado de su libertad, sino con la observancia de lo establecido en este artículo y en los casos y en la forma previstos en la ley. La detención preventiva no podrá durar más del tiempo estrictamente necesario para la realización de las averiguaciones tendentes al esclarecimiento de los hechos, y, en todo caso, en el plazo máximo de setenta y dos horas, el detenido deberá ser puesto en libertad o a disposición de la autoridad judicial.', tags: ['libertad', 'detención', 'seguridad', '72 horas', 'derechos'], relatedArticles: ['ces_15', 'ces_18'] },
  { id: 'ces_18', number: '18', title: 'Derecho al Honor e Intimidad', text: 'Se garantiza el derecho al honor, a la intimidad personal y familiar y a la propia imagen. El domicilio es inviolable. Ninguna entrada o registro podrá hacerse en él sin consentimiento del titular o resolución judicial, salvo en caso de flagrante delito. Se garantiza el secreto de las comunicaciones y, en especial, de las postales, telegráficas y telefónicas, salvo resolución judicial.', tags: ['honor', 'intimidad', 'domicilio', 'inviolable', 'comunicaciones'], relatedArticles: ['ces_17', 'ces_20'] },
  { id: 'ces_19', number: '19', title: 'Libertad de Residencia y Circulación', text: 'Los españoles tienen derecho a elegir libremente su residencia y a circular por el territorio nacional. Asimismo, tienen derecho a entrar y salir libremente de España en los términos que la ley establezca. Este derecho no podrá ser limitado por motivos políticos o ideológicos.', tags: ['residencia', 'circulación', 'libertad', 'movimiento', 'territorio'], relatedArticles: ['ces_17', 'ces_18'] },
  { id: 'ces_20', number: '20', title: 'Libertad de Expresión', text: 'Se reconocen y protegen los derechos: a expresar y difundir libremente los pensamientos, ideas y opiniones mediante la palabra, el escrito o cualquier otro medio de reproducción; a la producción y creación literaria, artística, científica y técnica; a la libertad de cátedra; y a comunicar o recibir libremente información veraz por cualesquiera medios de difusión.', tags: ['libertad de expresión', 'prensa', 'información', 'censura', 'medios'], relatedArticles: ['ces_18', 'ces_14'] },
  { id: 'ces_24', number: '24', title: 'Derecho a la Tutela Judicial', text: 'Todas las personas tienen derecho a obtener la tutela efectiva de los jueces y tribunales en el ejercicio de sus derechos e intereses legítimos, sin que, en ningún caso, pueda producirse indefensión. Asimismo, todos tienen derecho al Juez ordinario predeterminado por la ley, a la defensa y a la asistencia de letrado, a ser informados de la acusación formulada contra ellos, a un proceso público sin dilaciones indebidas y con todas las garantías.', tags: ['tutela judicial', 'juicio justo', 'defensa', 'abogado', 'proceso'], relatedArticles: ['ces_17', 'ces_25'] },
  { id: 'ces_25', number: '25', title: 'Principio de Legalidad Penal', text: 'Nadie puede ser condenado o sancionado por acciones u omisiones que en el momento de producirse no constituyan delito, falta o infracción administrativa, según la legislación vigente en aquel momento. Las penas privativas de libertad y las medidas de seguridad estarán orientadas hacia la reeducación y reinserción social y no podrán consistir en trabajos forzados.', tags: ['legalidad', 'delito', 'pena', 'reinserción', 'nulla poena'], relatedArticles: ['ces_24', 'ces_17'] },
]

const spainCodigoPenal = [
  { id: 'cpes_138', number: '138', title: 'Homicidio', text: 'El que matare a otro será castigado, como reo de homicidio, con la pena de prisión de diez a quince años. Si la víctima del delito previsto en el apartado anterior fuera menor de dieciséis años de edad o se trate de una persona especialmente vulnerable por razón de su edad, enfermedad o discapacidad, la pena será de prisión de quince a veinticinco años.', tags: ['homicidio', 'matar', 'prisión', 'delito', 'penal'], relatedArticles: ['cpes_139', 'cpes_140'] },
  { id: 'cpes_139', number: '139', title: 'Asesinato', text: 'Será castigado con la pena de prisión de quince a veinticinco años, como reo de asesinato, el que matare a otro concurriendo alguna de las circunstancias siguientes: 1ª Con alevosía. 2ª Por precio, recompensa o promesa. 3ª Con ensañamiento, aumentando deliberada e inhumanamente el dolor del ofendido. 4ª Para facilitar la comisión de otro delito o para evitar que se descubra.', tags: ['asesinato', 'alevosía', 'premeditación', 'precio', 'agravante'], relatedArticles: ['cpes_138', 'cpes_140'] },
  { id: 'cpes_234', number: '234', title: 'Hurto', text: 'El que, con ánimo de lucro, tomare las cosas muebles ajenas sin la voluntad de su dueño será castigado, como reo de hurto, con la pena de prisión de seis a dieciocho meses si la cuantía de lo sustraído excediese de 400 euros. Se impondrá una pena de multa de uno a tres meses si la cuantía de lo sustraído no excediese de 400 euros, salvo si concurriese alguna de las circunstancias del artículo 235.', tags: ['hurto', 'robo', 'sustracción', 'ánimo de lucro', '400 euros'], relatedArticles: ['cpes_237', 'cpes_242'] },
  { id: 'cpes_237', number: '237', title: 'Robo', text: 'Son reos del delito de robo los que, con ánimo de lucro, se apoderaren de las cosas muebles ajenas empleando fuerza en las cosas para acceder al lugar donde éstas se encuentran o para abandonarlo, o violencia o intimidación en las personas.', tags: ['robo', 'violencia', 'intimidación', 'fuerza', 'delito'], relatedArticles: ['cpes_234', 'cpes_242'] },
  { id: 'cpes_248', number: '248', title: 'Estafa', text: 'Cometen estafa los que, con ánimo de lucro, utilizaren engaño bastante para producir error en otro, induciéndolo a realizar un acto de disposición en perjuicio propio o ajeno. Los reos de estafa serán castigados con la pena de prisión de seis meses a tres años. Para la fijación de la pena se tendrá en cuenta el importe de lo defraudado, el quebranto económico causado al perjudicado, las relaciones entre éste y el defraudador, los medios empleados por éste y cuantas otras circunstancias sirvan para valorar la gravedad de la infracción.', tags: ['estafa', 'fraude', 'engaño', 'ánimo de lucro', 'perjuicio'], relatedArticles: ['cpes_234', 'cpes_249'] },
]

// ============================================================
// MERGE ALL INTO FILES
// ============================================================

const BASE = join(__dirname, '..', 'src', 'data')

console.log('Seeding top-50 curated articles...\n')

console.log('🇺🇸 USA:')
mergeArticles(join(BASE, 'usa', 'usConstitution.json'), usConstitution)
mergeArticles(join(BASE, 'usa', 'title18Criminal.json'), title18)
mergeArticles(join(BASE, 'usa', 'title42CivilRights.json'), title42)
mergeArticles(join(BASE, 'usa', 'title8Immigration.json'), title8)

console.log('\n🇧🇷 Brazil:')
mergeArticles(join(BASE, 'brazil', 'constituicao.json'), brazilConstituicao)
mergeArticles(join(BASE, 'brazil', 'codigoPenal.json'), brazilCodigoPenal)

console.log('\n🇵🇹 Portugal:')
mergeArticles(join(BASE, 'portugal', 'constituicaoPT.json'), portugalConstituicao)
mergeArticles(join(BASE, 'portugal', 'codigoPenalPT.json'), portugalCodigoPenal)

console.log('\n🇪🇸 Spain:')
mergeArticles(join(BASE, 'spain', 'constitucionES.json'), spainConstitucion)
mergeArticles(join(BASE, 'spain', 'codigoPenalES.json'), spainCodigoPenal)

console.log('\n✓ Done! Restart dev server to see changes.')
